#server:
#  port: 8080
#  servlet:
#    context-path: /community


#spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/community?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
#    username: root
#    password: 123456
#    druid:
#      initial-size: 5
#      min-idle: 5
#      max-active: 15
#      max-wait: 30000
#
#spring:
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/community?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
#    username: root
#    password: 123456
#    hikari:
#      minimum-idle: 5
#      maximum-pool-size: 15
#      idle-timeout: 30000

#logging:
#  level:
#    com.zfx.community: debug
